### ISSUE TITLE
Change landing page content

### ISSUE THREAD

**Issue by cflsdeboer** [cfl/issues_tptd#12]
The landing page content needs to change to the below content.  This content needs to be converted to proper HTML, replacing a lot of the dots, numbers, quotes, and other things into HTML entities.

The section headers:
* do not need to be numbered
* should be clearly clickable
* unhide/hide the content of their section

This image is for the area indicated below.

<img width="820" alt="TPTD Workflow Graphic" src="https://user-images.githubusercontent.com/89046687/184645051-47061c43-7b73-4e28-9350-94215cd97fbc.PNG">

==== begin included content ====

From this website, your team will be able to provide the league office with key information on your partnerships so that CFLV sponsorship asset inventory can be tracked, and so that teams and the league office can optimally coordinate around sales efforts that include CFLV sponsorship assets. Ultimately, this website supports teams in building out deal plans for ongoing sponsorship discussions – to confirm rate card requirements and deal value planning, to submit

The Team Partnership Tracking Document (TPTD) is a database used to collect key information on team partnerships league-wide, so that CFLV sponsorship asset inventories and sales reporting can be tracked to optimally coordinate sales efforts. Ultimately, this website supports teams in building out deal plans for ongoing sponsorship discussions, and ensures adherence to the new commercial model with the goal of optimizing overall sponsorship revenues.

The website consists of four areas:

Reporting
Partners 
Agreements
Leaseback 
 

Overall, the below diagram demonstrates the workflows that CFL teams should follow as part of the CFL Ventures sponsorship inventory management system.

 (insert attached graphic)

 

1. Analyzing and Monitoring Inventory Insights:

The dashboards and reports made available to the teams in TPTD help to understand and track:
CFLV asset quantities: total available, sold vs. unsold, leased
Overall sponsorship revenues
Per asset sponsorship sell-through amounts
Current partner deal info
INSTRUCTIONS – POWERBI DASHBOARDS:
·         Use the PoweBI dashboards to:

a.    To understand and analyze the big picture of your team’s sponsorship practice - as it relates to deals that contain CFLV assets

b.    To analyze sales data asset by asset (across CFLV assets)

c.     To stay on top of CFLV asset quantities so that you can effectively sell new partnerships and identify incremental leaseback needs

 

SALES OVERVIEW:

·         Navigate and interpret charts, KPIs, and reports on the SALES OVERVIEW tab to gain an understanding of:

·         Total Revenues by Season and by Partner*

·         CFLV Revenues by Season and by Partner*

·         # of Agreements, Average Agreement Revenue, Average Agreement CFLV Sales

·         Drill-through to see detailed tables that outline:

·         Partner-specific sales insights

·         Sales break-downs for each CFLV asset type

*Note that the TPTD only contains data entered for agreements that include CFLV assets

SALES INSIGHTS:

·         Navigate and interpret charts, KPIs, and reports on the SALES INSIGHTS tab to gain an understanding of:

·         CFLV Asset Sale Values vs.Rate Card Values by CFLV Asset Inventory - sorted by Asset Category, filterable by timing orientation, season, or asset type

·         Drill-through to see detailed tables that outline:

·         Overviews of partner by partner revenues and quantities for each CFLV asset category

·         Game by Game CFLV asset quantity and revenue break-downs (for Signage assets that can be sold on a per game basis)

INVENTORY TRACKING:

·         Navigate and interpret charts, KPIs, and reports on the INVENTORY TRACKING tabs to gain an understanding of:

·         Quantity of assets sold, and quantity remaining unsold for upcoming seasons and games

·         Quantity of sold/unsold assets for individual games

·         Quantity of previously leased assets to identify whether an incremental leaseback is needed for any new agreements

·         Inventory sell-through status, for each CFLV asset category, as a percentage of leased units and total units

 

2. Building a Deal Plan:

The creation of an agreement in TPTD can serve as a tentative deal plan before it is finalized and submitted for league approval. When pitching a partner or finalizing terms on a deal, this deal plan can allow the team to confirm minimum rate card values for CFLV assets, and also allow them to confirm that they have already leased sufficient quantities of the required CFLV assets
o    INSTRUCTIONS – "CREATE PARTNER":

§  Within the "Partners" page

§  Click "Create Partner"

§  Enter a "Short" name for the partner as well as a "Full Name"

§  Click "Submit"

o    INSTRUCTIONS – "CREATE AGREEMENT" FORM:

§  *Prior to submitting an Agreement, each team should create a profile for their partners in the Partners page. This will then allow for that company to be selected as the partner when an agreement submission form is built out.

§  Each Agreement submitted via this form represents an actual sponsorship agreement, containing CFLV assets, that ultimately requires league approval.

§  In the Agreements section, click "Create Agreement"

§  Deal Terms, provide six key pieces of information pertaining to the agreement:

§  Team

§  Partner

§  Grandfathered Deal? (if the deal was signed before 2022, no minimum rate card values will apply)

§  Inclusion of Standard Clauses

§  Renewal Clause

§  Start Year

§  AGREEMENT SUMMARY:

§  In addition to the asset-by-asset details of the deal (provided via the Sponsorship Deal Breakdown), the team is required to provide the Full Deal Value* at the top of the tab. NOTE: Deal value is defined by the team based on cash and VIK compensation received.

§  This information is required for league data analysis purposes and is also needed in order to calculate the minimum rate card value for any exclusivity add-on categories (although the minimum rate card value has been waived in 2022 for category exclusivity assets).

§  *the Full Deal Value entered by the team must exclude the value of Level 1 or Level 2 Add-On Categories since the value of those assets is calculated based upon this Full Deal Value amount

§  SPONSORSHIP DEAL BREAKDOWN:

§  For the agreement, each year's allocation of a given CFLV asset will need to be entered as a new item within the Sponsorship Deal Breakdown section

§  For each CFLV asset, input the corresponding "Season", "Scope", "Number of", and “Sold $”. Feel free to also provide a “Note” if any additional information is needed for the league office.

§  Depending on the Asset Type selected, you will see additional instructions and minimum rate card values to guide you as you input this information.

§  Note that for any "add-on" categories in the deal, the minimum rate card instructions will only be calculated once the Full Deal Value (excluding add-on categories) is entered (although the minimum rate card value has been waived in 2022 for category exclusivity assets).

 

3. Submitting a Leaseback Request:

Beyond the up-front leaseback quantities each season, there may be a need for a team to lease back incremental CFLV assets from the league in order to sell new agreements after all of the initially leased CFLV assets have been sold.
Leaseback requests will be reviewed by the league and approved based on available remaining unsold inventories, and the status of current new business conversations. These incremental leaseback requests will require a separate leaseback agreement whereby the team will purchase back the CFLV assets for resale.
 

o    INSTRUCTIONS – LEASEBACK REQUEST:

o    NOTE: Before creating a leaseback request:

·         Prior to building a leaseback request, It is recommended that you monitor the inventory data within TPTD dashboards and reports to ensure you’re fully aware of the availability of assets for lease (based on what has already been sold by the team and by the league).

·         It is also recommended that an Agreement draft be created for a new potential agreement as part of the deal planning. Within the Agreement form you can benefit from the reminders pertaining to asset unit definitions and minimum rate card values, so that you can be extra certain of the quantities to include in your leaseback request. 

·         To create a leaseback request, select “Create Leaseback” from the “LEASEBACK” page:

·         In the “Details” section of the form, give your leaseback request a name, and indicate the party that you’re requesting to lease assets from (typically the “CFL”)

·         Select the Season, Asset, Scope, and Quantity for each asset that will be included in the leaseback request. 

·         Select “Save Lease”

·         From the Leaseback page, select “Edit” or “Delete” as needed while you finalize your decision to make a leaseback request.

·         When you’re sure that the request is ready for submission (based on the leaseback fees and asset quantities involved), select “Tender”

 

 4. Sold Agreement Submission / Approval Request:

Once all of the asset quantities and details have been confirmed, and the team has secured any CFLV asset leases required, an agreement can be submitted for final league approval.
o    INSTRUCTIONS – AGREEMENT SUBMISSION:

§  When a deal plan has been saved and is ready for league review, submit it by selecting “Tender” within the Action column (in the “Agreements” page). Once tendered, the “Approval status” column will update from Drafting to Pending.

§  A submitted agreement that has been tendered for league review will convert from a Pending status to Approved once the league has verified that standard clauses are included, all assets in the deal are available and that minimum rate card values have been met by the sale.

§  If an agreement has been tendered for league review but needs to be edited or deleted, it must first be withdrawn from the league review process by selecting “Withdraw Submission” within the Action column (in the “Agreements” page). Once withdrawn, the “Approval status” column will update from Pending to Drafting.

**Comment by aquiceno** [comment]
The page content was updated.
